Train:
  batch_size: 128
  learning_rate: 2
  reg: 0.0001
  epochs: 20
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 128 # only applicable for TwolayerNet
